# Site settings
title: Why Privacy Matters
logo: assets/icon.png
description: Privacy is important. Here are some simple reasons why.
url: https://whyprivacymatters.org
lang: en
repository: milesmcc/whyprivacymatters

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-github-metadata

# Build Settings
permalink: :title/
sass:
  sass_dir: css
  style: compressed

webmaster_verifications:
  google: YeDX7szNUt5VC8TQGBVYZVJfAKRMQJgssEebvdAodhk

# Paths
defaults:
  -
    scope:
      path: "README.md"
    values:
      permalink: "/"
